### ISSUE TITLE
crashes on ios app 

### ISSUE THREAD

**Issue by xDPixel** [tatsuz0u/ehpanda-website#1]
Hi, I have a sideloading store, tried to upload the app for subscribers but they said it crashes once started, I tried myself and I got the crashes also. I also tried to install via trollstore and got crash. Here's crash log 

```
Date: 11/11/24, 2:42 PM
Process: EhPanda
Bundle id: app.ehpanda
Device: iPhone 14 Pro, iOS 16.5
Bundle version: 2.7.8

Exception type: EXC_SOFTWARE (SIGABRT)
Exception subtype: EXC_UNIX_ABORT
Exception codes: 0x0000000000010002, 0x0000000000000000
Culprit: Unknown
Termination Reason: Library not loaded: /usr/lib/swift/libswiftObservation.dylib
  Referenced from: &lt;9622156D-DAAD-36E2-89DB-427BE6F7F001&gt; /private/var/containers/Bundle/Application/391A981A-C2CF-4063-B4C4-8A3F27016C40/EhPanda.app/EhPanda (built for iOS 17.0 which is newer than running OS)
  Reason: tried: '/usr/lib/swift/libswiftObservation.dylib' (no such file), '/private/preboot/Cryptexes/OS/usr/lib/swift/libswiftObservation.dylib' (no such file), '/usr/lib/swift/libswiftObservation.dylib' (no such file, not in dyld cache)

Triggered by thread: 0
Thread name: (null)
Call stack:
0   dyld                                0x00000001a98fdfcc 0x1a9891000 + 0x6cfcc          // __abort_with_payload
1   dyld                                0x00000001a9908b18 0x1a9891000 + 0x77b18          // abort_with_payload_wrapper_internal
2   dyld                                0x00000001a9908b4c 0x1a9891000 + 0x77b4c          // abort_with_payload
3   dyld                                0x00000001a98ab004 0x1a9891000 + 0x1a004          // dyld4::halt(char const*)
4   dyld                                0x00000001a98a930c 0x1a9891000 + 0x1830c          // dyld4::prepare(dyld4::APIs&amp;, dyld3::MachOAnalyzer const*)
5   dyld                                0x00000001a98a6cdc 0x1a9891000 + 0x15cdc          // start

Register values:
PC: 0x16f172750         LR: 0x16f172790         CPSR: 0xa98fdfcc
x0: 0x4400000006        x1: 0x6                 x2: 0x1
x3: 0x16f172bc0         x4: 0xa1                x5: 0x16f1727c0
x6: 0x0                 x7: 0x0                 x8: 0x510
x9: 0x20                x10: 0x9                x11: 0x1
x12: 0xa                x13: 0x0                x14: 0x33
x15: 0x4                x16: 0x8000             x17: 0x209
x18: 0x1a98fb4b8        x19: 0x0                x20: 0x0
x21: 0x16f1727c0        x22: 0xa1               x23: 0x16f172bc0
x24: 0x1                x25: 0x6                x26: 0x0
x27: 0x0                x28: 0x16f173580

Loaded images:
0: /private/var/containers/Bundle/Application/391A981A-C2CF-4063-B4C4-8A3F27016C40/EhPanda.app/EhPanda
1: /usr/lib/systemhook-077DD1FC464BC49E.dylib
2: /usr/lib/dyld


{"ProcessBundleID":"app.ehpanda","ProcessName":"EhPanda","Culprit":"Unknown"}
```

after viewing the crash log I realized that app built for iOS17 and above according to the line `built for iOS 17.0 which is newer than running OS` , so if you -please- can re-build it with support for lower iOS versions as low as you can. Thank you!

**Comment by tatsuz0u** [comment]
Thanks for your feedback. Wrong repository to submit this issue though XD. Please submit EhPanda app related issues to the main app repository which just named "EhPanda" next time.

I'm sorry to hear that you and your store's subscribers are experiencing the crash issue when EhPanda launches. And yes it seems that the system version requirement is causing that issue.

Unfortunately, it’s not as straightforward to make the app compatible with older versions. It needs alternative implementations in various parts of the entire app where the latest APIs are used. This is a significant amount of work that may not be feasible given the resources available to the EhPanda team.

**Comment by xDPixel** [comment]
Thank you for your detailed response, and my apologies for submitting the issue in the wrong repository! I was opening ∞ tabs so thought that I was in the correct repository.
I understand that making the app compatible with older system versions is no small task and that it requires considerable resources. I appreciate you taking the time to explain the situation, and I’m grateful for all the work your team puts into the app.
Thanks again for your response.
